replicaCount: 1

image:
  repository: 742348407315.dkr.ecr.eu-central-1.amazonaws.com/eks-repository   # replace with your image name
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
